"""
pyroclastic_flow.py
==================
Pyroclastic density currents (PDCs): fast, ground-hugging avalanches of
hot gas and volcanic debris generated by column collapse. These are the
deadliest volcanic hazard and the centrepiece of the hazard analysis.

Model: gravity-driven particles that follow the terrain surface, accelerate
downslope, decelerate by Coulomb-like friction, and stop where the
"energy line" (Heim coefficient H/L) intersects topography. A terrain
height-sampling callback couples the flow to the DEM.
"""

import numpy as np

from .particle_system import ParticleSystem
from .physics import GRAVITY, pdc_front_velocity, energy_cone_runout


class PyroclasticFlow(ParticleSystem):
    def __init__(self, render_root, vent_pos, terrain_sampler,
                 heim_coefficient=0.25, collapse_height=2000.0,
                 max_particles=6000):
        super().__init__(render_root, max_particles, point_size=14.0,
                         additive=False, name="pyroclastic_flow")
        self.vent_pos = np.asarray(vent_pos, dtype=np.float32)
        self.sample_height = terrain_sampler     # f(x, y) -> ground z
        self.heim = heim_coefficient
        self.collapse_height = collapse_height
        self.friction = heim_coefficient         # tan(repose) ~ H/L
        # Energy line origin: top of collapsing column above vent
        self.energy_origin_z = self.vent_pos[2] + collapse_height
        self.max_runout = energy_cone_runout(collapse_height, heim_coefficient)
        self.hover = 25.0                        # ride height above ground [m]

    # ------------------------------------------------------------------
    def trigger_collapse(self, n_particles=2500):
        """Column collapse: launch a radial surge of PDC particles."""
        for _ in range(int(n_particles)):
            ang = np.random.uniform(0, 2 * np.pi)
            speed = np.random.uniform(40, 90)
            vel = np.array([speed * np.cos(ang), speed * np.sin(ang),
                            np.random.uniform(-5, 5)], dtype=np.float32)
            start = self.vent_pos + np.array(
                [np.random.uniform(-40, 40), np.random.uniform(-40, 40),
                 np.random.uniform(20, 120)], dtype=np.float32)
            color = np.array([0.32, 0.30, 0.30, 0.9], dtype=np.float32)
            super().emit(start, vel, color,
                         lifetime=np.random.uniform(40, 80),
                         size=np.random.uniform(1.0, 2.2))

    # ------------------------------------------------------------------
    def update_physics(self, dt):
        live = self.alive
        if not live.any():
            return
        idx = np.where(live)[0]
        pos = self.pos[idx]
        vel = self.vel[idx]

        # Ground following: sample terrain under each particle
        ground = np.array([self.sample_height(p[0], p[1]) for p in pos],
                          dtype=np.float32)
        target_z = ground + self.hover

        # Distance from vent (horizontal) for energy-line stopping
        dx = pos[:, 0] - self.vent_pos[0]
        dy = pos[:, 1] - self.vent_pos[1]
        dist = np.sqrt(dx * dx + dy * dy) + 1e-3

        # Energy line height at this distance: z_E = origin - heim * L
        energy_z = self.energy_origin_z - self.heim * dist
        # Flow stops where terrain rises above the energy line
        stopped = ground >= energy_z

        # Local slope estimate via finite differences on the DEM
        eps = 30.0
        hx = (np.array([self.sample_height(p[0] + eps, p[1]) for p in pos]) -
              np.array([self.sample_height(p[0] - eps, p[1]) for p in pos])) / (2 * eps)
        hy = (np.array([self.sample_height(p[0], p[1] + eps) for p in pos]) -
              np.array([self.sample_height(p[0], p[1] - eps) for p in pos])) / (2 * eps)
        slope_mag = np.sqrt(hx * hx + hy * hy)

        # Gravity drives flow downslope (-grad h direction)
        gx = -GRAVITY * hx
        gy = -GRAVITY * hy
        # Coulomb friction opposes motion
        speed = np.sqrt(vel[:, 0] ** 2 + vel[:, 1] ** 2) + 1e-3
        fric = self.friction * GRAVITY
        fx = -fric * vel[:, 0] / speed
        fy = -fric * vel[:, 1] / speed

        vel[:, 0] += (gx + fx) * dt
        vel[:, 1] += (gy + fy) * dt

        # Clamp to physical PDC front speeds
        speed = np.sqrt(vel[:, 0] ** 2 + vel[:, 1] ** 2)
        over = speed > 120.0
        vel[over, 0] *= 120.0 / speed[over]
        vel[over, 1] *= 120.0 / speed[over]

        # Apply stopping (energy line reached): freeze horizontal motion
        vel[stopped, 0] *= 0.02
        vel[stopped, 1] *= 0.02

        # Vertical: snap toward terrain-following height
        vel[:, 2] = (target_z - pos[:, 2]) * 4.0

        # Integrate
        pos += vel * dt
        self.pos[idx] = pos
        self.vel[idx] = vel

    # ------------------------------------------------------------------
    def update_appearance(self):
        live = self.alive
        if not live.any():
            return
        life_frac = np.clip(self.age[live] / self.lifetime[live], 0, 1)
        speed = np.sqrt(self.vel[live, 0] ** 2 + self.vel[live, 1] ** 2)
        hot = np.clip(speed / 90.0, 0, 1)         # faster = hotter glow
        # Hot grey-brown with incandescent tint at the fast-moving front
        self.color[live, 0] = 0.30 + 0.55 * hot
        self.color[live, 1] = 0.28 + 0.18 * hot
        self.color[live, 2] = 0.27
        self.color[live, 3] = (1.0 - life_frac) * 0.9
